cs412/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from cs412 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('quotes/', include('quotes.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('mini_fb/', include('mini_fb.urls')),
    path('voter_analytics/', include('voter_analytics.urls')),
    path('pokemon_app/', include('pokemon_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pokemon_app/urls.py
# File: urls.py
# Author: John kim (johnjk@bu.edu), 12/01/2024
# Description: this file sets the URL patterns for pokemon app

from django.urls import path
from django.contrib.auth import views as auth_views 
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path(r'', views.ShowAllProfilesView.as_view(), name='show_all_profiles'),
  path(r'profiles', views.ShowAllProfilesView.as_view(), name='show_all_profiles'),
  path(r'profile/<int:pk>/', views.ShowProfilePageView.as_view(), name='show_profile'),
  path(r'create_profile/', views.CreateProfileView.as_view(), name='create_profile'),
  path('pokedex/', views.PokeDexListView.as_view(), name='pokedex'),
  path('pokedex/<int:pk>/', views.PokeDexDetailView.as_view(), name='pokedex_detail'),
  path(r'login/', auth_views.LoginView.as_view(template_name='pokemon_app/login.html'), name='login'),
  path(r'logout/', auth_views.LogoutView.as_view(template_name='pokemon_app/logged_out.html'), name='logout'),
  path(r'add_pokemon/', views.AddPokemonView.as_view(), name='add_pokemon'),
  path(r'trade/create/', views.CreateTradeView.as_view(), name='create_trade'),
  path(r'trade/<int:pk>/', views.ViewTradeView.as_view(), name='trade_detail'),
  path(r'trade/<int:pk>/accept/', views.AcceptTradeView.as_view(), name='accept_trade'),
  path(r'trade/<int:pk>/reject/', views.RejectTradeView.as_view(), name='reject_trade'),
  path(r'trade/all/', views.ViewAllTradesView.as_view(), name='show_all_trades'),
  path(r'profile/<int:pk>/update/', views.EditProfileView.as_view(), name='update_profile'),
  path('graphs/', views.GraphsListView.as_view(), name='pokemon_graphs'),
  path(r'pokemon/<int:pk>/remove', views.RemovePokemonView.as_view(), name='remove_pokemon'),
]

pokemon_app/models.py
# File: models.py
# Author: John kim (johnjk@bu.edu), 11/22/2024
# Description: this file models the data attributes of the pokemon application

from django.db import models
import os
import csv
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.  
class Profile(models.Model):
  '''
  user model for the pokemon app
  '''
  user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="pokemon_profile")
  first_name = models.TextField()
  last_name = models.TextField()
  email = models.EmailField()
  profile_pfp = models.URLField(blank=False)
  joined_on = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    '''
    returns a string representation of Profile
    '''
    return f"{self.first_name} {self.last_name} joined on {self.joined_on}"
  
  def get_absolute_url(self):
    '''
    returns url to show the one profile
    '''
    return reverse('show_profile', kwargs={'pk': self.pk})
  


class PokeDex(models.Model):
  """
  PokeDex model to store detailed Pokémon data.
  """
  name = models.CharField(max_length=100)
  type1 = models.CharField(max_length=50)
  type2 = models.CharField(max_length=50, blank=True, null=True)
  species = models.CharField(max_length=100)
  height = models.CharField(max_length=50)  
  weight = models.CharField(max_length=50) 
  abilities = models.TextField()  
  ev_yield = models.CharField(max_length=100)  
  catch_rate = models.CharField(max_length=100)  
  base_friendship = models.CharField(max_length=50) 
  base_exp = models.IntegerField()
  growth_rate = models.CharField(max_length=50) 
  egg_groups = models.CharField(max_length=100) 
  gender_ratio = models.CharField(max_length=50)
  egg_cycles = models.CharField(max_length=50)  
  base_hp = models.IntegerField()
  base_atk = models.IntegerField()
  base_def = models.IntegerField()
  base_sp_atk = models.IntegerField()
  base_sp_def = models.IntegerField()
  base_speed = models.IntegerField()
  pokemon_image = models.ImageField(upload_to='Pokemon_images/', blank=True, null=True)

  def __str__(self):
    return f"{self.name}"  

class Pokemon(models.Model):
  '''
  pokemon model for the pokemon app
  '''
  nickname = models.TextField(blank=True, null=True)
  species = models.ForeignKey(PokeDex, on_delete=models.CASCADE)
  level = models.IntegerField()
  trainer = models.ForeignKey(Profile, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.nickname if self.nickname else self.species} owned by {self.trainer.first_name} {self.trainer.last_name}"
  

class Trade(models.Model):
  '''
  trade model for the pokemon app
  '''
  proposer = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='proposer')
  receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
  pokemon_offer = models.ForeignKey(Pokemon, on_delete=models.CASCADE, related_name='offer')
  pokemon_request = models.ForeignKey(Pokemon, on_delete=models.CASCADE, related_name='request')
  status_choices = [
    ('in_progress', 'In Progress'),
    ('accepted', 'Accepted'),
    ('rejected', 'Rejected')
  ]
  status = models.CharField(max_length=12, choices=status_choices, default='in_progress')
  trade_date = models.DateTimeField(blank=True, null=True)

  def __str__(self):
    return f"{self.proposer.first_name}: {self.pokemon_offer.species} for {self.pokemon_request.species}"


def load_data():
    """
    Function to load Pokémon data into the database for generations 1-6.
    """
    # remove existing data
    PokeDex.objects.all().delete()

    # some filepaths
    filename = '/Users/johnkim/Downloads/pokemonDB_dataset.csv'
    image_path = 'Pokemon_images'

    with open(filename, 'r') as f:
        reader = csv.reader(f)  # CSV reader for parsing
        headers = next(reader)  # skips headers

        for fields in reader:
            try:
                # splits and parses the fields
                types = fields[1].split(', ')
                t1 = types[0]
                t2 = types[1] if len(types) > 1 else None

                # makes an image path from the images folder MEDIA
                image_name = f"{fields[0]}/{fields[0]}.png"
                pokemon_image = os.path.join(image_path, image_name)

                # numeric conversion helper
                def parse_int(value):
                    return int(value) if value.isdigit() else 0

                # makes the Pokedex entry
                pokedex = PokeDex(
                    name=fields[0],  # Pokémon name
                    type1=t1, # type 1
                    type2=t2, # type 2
                    species=fields[2],  # Species
                    height=fields[3],  # Height
                    weight=fields[4],  # Weight
                    abilities=fields[5],  # Abilities
                    ev_yield=fields[6],  # EV Yield
                    catch_rate=fields[7],  # Catch Rate
                    base_friendship=fields[8],  # Base Friendship
                    base_exp=parse_int(fields[9]),  # Base EXP
                    growth_rate=fields[10],  # Growth Rate
                    egg_groups=fields[11],  # Egg Groups
                    gender_ratio=fields[12],  # Gender Ratio
                    egg_cycles=fields[13],  # Egg Cycles
                    base_hp=parse_int(fields[14]),  # Base HP
                    base_atk=parse_int(fields[15]),  # Base Attack
                    base_def=parse_int(fields[16]),  # Base Defense
                    base_sp_atk=parse_int(fields[17]),  # Base Special Attack
                    base_sp_def=parse_int(fields[18]),  # Base Special Defense
                    base_speed=parse_int(fields[19]),  # Base Speed
                    pokemon_image=pokemon_image  # Path to the image
                )
                pokedex.save()
                print(f"Created PokeDex entry: {pokedex.name}")

            except Exception as e:
                print(f"Error creating PokeDex entry for line: {fields}")
                print(f"Error details: {e}")

    print("Done loading data.")

pokemon_app/forms.py
# File: forms.py
# Author: John kim (johnjk@bu.edu), 12/09/2024
# Description: file controls the forms for mini_fb

from django import forms
from .models import Profile, Pokemon, Trade

class CreateProfileForm(forms.ModelForm):
  '''
  form to create profile data
  '''

  class Meta:
    '''
    assigns model and fields to form
    '''
    model = Profile
    fields = ['first_name', 'last_name', 'email', 'profile_pfp']

class CreatePokemonForm(forms.ModelForm):
  '''
  form to create pokemon data
  '''

  class Meta:
    '''
    assigns model and fields to form
    '''
    model = Pokemon
    fields = ['species', 'nickname', 'level']

class CreateTradeForm(forms.ModelForm):
  '''
  form to trade pokemon data
  '''
  
  class Meta:
    '''
    assigns model and fields to form
    '''
    model = Trade
    fields = ['pokemon_offer', 'pokemon_request', 'receiver']

pokemon_app/templates/pokemon_app/add_pokemon.html
<!-- 
 File: add_pokemon.html
 Author: John kim (johnjk@bu.edu), 12/10/2024
 Description: this file is the add pokemon form for adding pokemon to user profiles
-->

{% extends 'pokemon_app/base.html' %}

{% block content %}
<h1>Add a Pokémon</h1>

<!-- form submits to add pokemon view to add to POKEMON table -->
<form class="add-pokemon-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Pokémon</button>
    <!-- User back button to profile in case they change their mind -->
    <a class="a-link" href="{% url 'show_profile' user.pokemon_profile.id %}">Back to Profile</a>
</form>
{% endblock %}

pokemon_app/templates/pokemon_app/base.html
<!-- 
 File: base.html
 Author: John kim (johnjk@bu.edu), 12/01/2024
 Description: this file is the base HTML template for pokemon
-->

{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- title specification -->
    <title>PokeInv</title>
    <!-- linking style -->
    <link rel="stylesheet" href="{% static 'paStyles.css' %}" />
  </head>
  <body>
    <!-- header -->
    <header>
      <!-- nav bar with all the buttons -->
      <nav class="nav">
        <ul>
          <!-- un login users alowed to see pokedex, profiles, and graphs -->
          <li><a class="a-link" href="{% url 'pokedex' %}">Pokedex</a></li>
          <li><a class="a-link" href="{% url 'show_all_profiles' %}">Profiles</a></li>
          <li><a class="a-link" href="{% url 'pokemon_graphs' %}">Graphs</a></li>
          <!-- if the user is logged in they can see their own profile and also logout -->
          {% if user.is_authenticated %}
            {% if user.pokemon_profile %}
              <li>
                <a class="a-link" href="{% url 'show_profile' user.pokemon_profile.id %}">Show My Profile</a>
              </li>
            {% endif %}
            <li>
              <form method="post" action="{% url 'logout' %}" class="logout-button">
                  {% csrf_token %}
                  <input class="a-link" type="submit" value="Logout" />
              </form>
            </li>
          <!-- unlogged in users are prompted to login or create a profile (register) -->
          {% else %}
            <li><a class="a-link" href="{% url 'login' %}">Login</a></li>
            <li><a class="a-link" href="{% url 'create_profile' %}">Register</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>

    <!-- block content -->
    {% block content %} {% endblock %}

  </body>
</html>

pokemon_app/templates/pokemon_app/confirm_trade.html
<!-- 
 File: confirm_trade.html
 Author: John kim (johnjk@bu.edu), 12/09/2024
 Description: this file is the form to confirm a trade proposal
-->
{% extends 'pokemon_app/base.html' %}

{% block content %}
<div class="confirm-trade">
  <!-- simple display to confirm -->
  <h2>Confirm Trade Action</h2>
  <p>
    Are you sure you want to 
    accept or reject
    this trade?
  </p>
  
  <!-- form submits to accept/reject view to confirm trades  -->
  <form method="post">
      {% csrf_token %}
      <button type="submit">Confirm</button>
      <a href="{% url 'show_profile' user.pokemon_profile.id %}" class="a-link">Cancel</a>
  </form>
</div>
{% endblock %}

pokemon_app/templates/pokemon_app/create_profile.html
<!-- 
 File: create_profile.html
 Author: John kim (johnjk@bu.edu), 12/09/2024
 Description: this file is the form to create profile
-->
{% extends 'pokemon_app/base.html' %}

{% block content %}
<h2>Create a New Profile!</h2>

<!-- tied in the django USER creation with my profile creation also to do 2 things at once -->
<form method="post" class="form-container">
  <table>
    {% csrf_token %}
    {{ user_form.as_table }}
    {{ form.as_table }}
    <tr>
      <td></td>
      <td><input type="submit" value="Create Profile"></td>
  </table>
</form>

{% endblock %}

pokemon_app/templates/pokemon_app/create_trade.html
<!-- 
 File: create_trade.html
 Author: John kim (johnjk@bu.edu), 12/09/2024
 Description: this file is the form to create a trade
-->
{% extends 'pokemon_app/base.html' %}

{% block content %}

<h2>Create a New Trade!</h2>

<!-- this is the form for users to fill out and thus create a trade proposal to other users -->
<form class="form-container" method="post" class="trade-form">
  {% csrf_token %}
  
  <!-- this dropdown accomodates the receiver as in who do you want to trade with -->
  <label class="trade-group" for="receiver">Choose a Trainer:</label>
  <select id="receiver" name="receiver">
      {% for profile in receivers %}
      <option value="{{ profile.id }}">{{ profile.first_name }} {{ profile.last_name }}</option>
      {% endfor %}
  </select>

  <!-- select one of your pokemon to trade with, nicknames respected -->
  <label class="trade-group" for="pokemon_offer">Your Pokémon:</label>
  <select id="pokemon_offer" name="pokemon_offer">
      {% for pokemon in proposer_pokemon %}
      <option value="{{ pokemon.id }}">{{ pokemon.nickname|default:pokemon.species.name }} (Level {{ pokemon.level }})</option>
      {% endfor %}
  </select>

  <!-- select one of their pokemon to take -->
  <label class="trade-group" for="pokemon_request">Requested Pokémon:</label>
  <select id="pokemon_request" name="pokemon_request">
      {% for pokemon in other_pokemon %}
      <option value="{{ pokemon.id }}">{{ pokemon.nickname|default:pokemon.species.name }} (Level {{ pokemon.level }})</option>
      {% endfor %}
  </select>

  {% if form.errors %}
    <div>
      <ul>
        {% for field in form %}
          {% for error in field.errors %}
            <li>{{ field.label }}: {{ error }}</li>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    </div>
  {% endif %}

  <button type="submit">Propose Trade</button>
  <a class="a-link" href="{% url 'show_profile' user.pokemon_profile.id %}">Back to Profile</a>
</form>

{% endblock %}

pokemon_app/templates/pokemon_app/edit_profile.html
<!-- 
 File: edit_profile.html
 Author: John kim (johnjk@bu.edu), 12/01/2024
 Description: this file allows you to edit your own profile
-->
{% extends 'pokemon_app/base.html' %}

{% block content %}
<h2>Edit Profile</h2>
<!-- this form displays a form as p with the filled out profile details so you can edit and save your changes -->
<form class="form-container" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save Changes</button>
  <a class="a-link" href="{% url 'show_profile' pk=profile.pk %}">Cancel</a>
</form>
{% endblock %}

pokemon_app/templates/pokemon_app/graphs.html
<!-- 
 File: graphs.html
 Author: John kim (johnjk@bu.edu), 12/10/2024
 Description: this file displays the 3 graphs for the pokemon analytics page
-->
{% extends 'pokemon_app/base.html' %}

{% block content %}
<div class="graph-container">
    <h1>Pokémon Analytics</h1>
    <!-- each of these graphs are self explanatory and uses plotly divs to display -->
    <div>
        <h2>Number of Pokémon Caught by User</h2>
        {{ caught_graph|safe }}
    </div>

    <div>
        <h2>Pokémon Types Caught by Users</h2>
        {{ type_graph|safe }}
    </div>

    <div>
        <h2>Most Traded Pokémon Species</h2>
        {{ traded_graph|safe }}
    </div>
</div>
{% endblock %}

pokemon_app/templates/pokemon_app/logged_out.html
<!-- 
 File: logged_out.html
 Author: John Kim (johnjk@bu.edu), 12/09/2024
 Description: This file shows the logout page
-->
{% extends 'pokemon_app/base.html' %} {% block content %}
<div class="logout">
  <h2>Logout</h2>

  <p>Logout Successful</p>
  <!-- redirects to login after logout if needed -->
  <a class="a-link" href="{% url 'login' %}">Login Again?</a>
</div>
{% endblock %}

pokemon_app/templates/pokemon_app/login.html
<!-- 
 File: login.html
 Author: John Kim (johnjk@bu.edu), 12/09/2024
 Description: This file shows the login page
-->
{% extends 'pokemon_app/base.html' %} 

{% block content %}
<h2>Login!</h2>

<!-- form takes in the details and then logs the user in afterwards -->
<form class="form-container" method="POST" action="{% url 'login' %}">
    {% csrf_token %}
    {{form}}
    <!-- what to do after login success -->
    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{request.GET.next}}">
    {% else %}
    <input type="hidden" name="next" value="{% url 'show_all_profiles' %}">
    {% endif %}
    <input type="submit" value="Login">
</form>
{% endblock %}

pokemon_app/templates/pokemon_app/pokedex_detail.html
<!-- 
 File: pokedex_detail.html
 Author: John kim (johnjk@bu.edu), 12/08/2024
 Description: this file shows one of the pokemon in the database
-->

{% extends 'pokemon_app/base.html' %} {% block content %}
<div class="pokemon-detail-container">
  <h1>{{ pokemon.name }}</h1>
  <!-- pokemon image card, this is where i do that cool flip animation -->
  <div class="pokemon-image-card">
    <div class="content">
      <div class="front">
        <img src="{{ pokemon.pokemon_image.url }}" alt="{{ pokemon.name }}" />
      </div>
      <div class="back">
        
      </div>
    </div>
  </div>

  <!-- displays the pokemon details from the pokedex -->
  <div class="pokemon-details">
    <p>
      Type:
      <span class="type1">{{ pokemon.type1 }}</span>
      {% if pokemon.type2 %}
      <span class="type2">{{ pokemon.type2 }}</span>
      {% endif %}
    </p>
    <p>Species: {{ pokemon.species }}</p>
    <p>Height: {{ pokemon.height }}</p>
    <p>Weight: {{ pokemon.weight }}</p>
    <p>Abilities: {{ pokemon.abilities }}</p>
    <p>Base Stats:</p>
    <ul>
      <li><span>HP:</span> {{ pokemon.base_hp }}</li>
      <li><span>Attack:</span> {{ pokemon.base_atk }}</li>
      <li><span>Defense:</span> {{ pokemon.base_def }}</li>
      <li><span>Special Attack:</span> {{ pokemon.base_sp_atk }}</li>
      <li><span>Special Defense:</span> {{ pokemon.base_sp_def }}</li>
      <li><span>Speed:</span> {{ pokemon.base_speed }}</li>
    </ul>
  </div>
  <!-- back to the pokedex for users -->
  <a href="{% url 'pokedex' %}" class="back-button">Back to Pokédex</a>
</div>

{% endblock %}

pokemon_app/templates/pokemon_app/pokedex_list.html
<!-- 
 File: pokedex_list.html
 Author: John kim (johnjk@bu.edu), 12/08/2024
 Description: this file shows all the pokemon in the database
-->
{% extends 'pokemon_app/base.html' %}
{% block content %}
<h1 class="pokedex-title">Pokédex</h1>

<!-- search form for querying pokemon by type, name, species -->
<form method="get" action="">
  <input type="text" name="search" placeholder="Search Pokémon by name, type, or species"
         value="{{ search }}" />
  <button type="submit">Search</button>
</form>

<div class="p-grid">
  <!-- displays the pokemon with their image and brief details  -->
  {% for pokemon in pokedex %}
  <div class="p-card-wrapper">
    <div class="p-card">
      <div class="p-card-header">
        <img
          src="{{ pokemon.pokemon_image.url }}"
          alt="{{ pokemon.name }} Image"
          class="p-card-image"
        />
      </div>
      <div class="p-card-body">
        <h2 class="p-card-title">{{ pokemon.name }}</h2>
        <p class="p-card-type">
          Type: <span class="type1">{{ pokemon.type1 }}</span>{% if pokemon.type2 %} / <span class="type2">{{ pokemon.type2 }}</span>{% endif %}
        </p>
        <!-- users can see specifics by clicking here to see extended details -->
        <a href="{% url 'pokedex_detail' pokemon.id %}" class="p-card-button">View Details</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

<div class="pagination">
  {% if is_paginated %}
  <ul>
    {% if page_obj.has_previous %}
    <li>
      <a href="?page={{ page_obj.previous_page_number }}" class="arrow prev" aria-label="Previous">
        &#9664; <!-- Left arrow -->
      </a>
    </li>
    {% endif %}

    <li class="page-info">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </li>

    {% if page_obj.has_next %}
    <li>
      <a href="?page={{ page_obj.next_page_number }}" class="arrow next" aria-label="Next">
        &#9654; <!-- Right arrow -->
      </a>
    </li>
    {% endif %}
  </ul>
  {% endif %}
</div>

{% endblock %}

pokemon_app/templates/pokemon_app/show_all_profiles.html
<!-- 
 File: show_all_profiles.html
 Author: John kim (johnjk@bu.edu), 12/01/2024
 Description: this file is the show_all_profiles HTML template for PokeInv
-->

{% extends 'pokemon_app/base.html' %} 
{% block content %}
<h2 class="prof-title">All Profiles</h2>

<div class="p-grid">
  <!-- fetches all profiles ato be displayed on this page -->
  {% for profile in profiles %}
  <div class="profile-card">
    <!-- by clicking, users can bring up a detailed profile page defined seperately -->
    <a class="p-link" href="{% url 'show_profile' profile.pk %}">
      <div class="profile-card-header">
        <img class="p-img" src="{{ profile.profile_pfp }}" alt="Profile Picture" />
      </div>
      <div class="profile-card-body">
        <h3 class="profile-name">{{ profile.first_name }} {{ profile.last_name }}</h3>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}

pokemon_app/templates/pokemon_app/show_profile.html
<!-- 
 File: show_profile.html
 Author: John kim (johnjk@bu.edu), 12/01/2024
 Description: this file is the show profile HTML template for pokemon_app
-->
{% extends 'pokemon_app/base.html' %}

{% block content %}
<div class="profile-container">
  <h1 class="prof-name">{{ profile.first_name }} {{ profile.last_name }}</h1>
  <img class="prof-pfp" src="{{ profile.profile_pfp }}" alt="Profile Picture" />
  <p class="prof-email">Email: {{ profile.email }}</p>

  <h2 class="prof-inv">PokeInv:</h2>
  <ul class="prof-ul">
    <!-- displays the pokemon list that the user possesses and displays none if they have none -->
    {% if pokemon_list %} 
      {% for pokemon in pokemon_list %}
        <li class="pokemon-item">
          <a href="{% url 'pokedex_detail' pokemon.species.id %}" class="pokemon-link">
            <img src="{{ pokemon.species.pokemon_image.url }}" alt="{{ pokemon.species.name }}" class="pokemon-icon" />
            <span class="pokemon-name">
              {{ pokemon.nickname|default:pokemon.species.name }} (Level {{ pokemon.level }})
            </span>
            <!-- removes your owned pokeomn -->
            {% if user.is_authenticated and user == profile.user %}
            <form method="post" action="{% url 'remove_pokemon' pokemon.id %}">
              {% csrf_token %}
              <button type="submit" class="a-link">Release Pokémon</button>
            </form>
            {% endif %}
          </a>
        </li>
      {% endfor %} 
    {% else %}
      <li class="no-pokemon">No Pokémon in Inventory</li>
    {% endif %}
  </ul>
  <div class="button-div">
    <div>
      <!-- only when the user is authenticated can they add pokemon -->
      {% if user.is_authenticated and user == profile.user %}
        <a href="{% url 'add_pokemon' %}" class="a-link">Add Pokemon</a>
      {% endif %}
    </div>
    <div>
      <!-- only when the user is authenticated can they propose a trade -->
      {% if user.is_authenticated and user.pokemon_profile.id == profile.id %}
        <a href="{% url 'create_trade' %}" class="a-link">Propose a Trade</a>
      {% endif %}
    </div>  
    <div>
      <!-- only when the user is authenticated can they view all trades -->
      {% if user.is_authenticated and user.pokemon_profile.id == profile.id %}
        <a href="{% url 'show_all_trades' %}" class="a-link">View All Trades</a>
      {% endif %}
    </div>
    <div>
      <!-- only when the user is authenticated and the profile is the user's profile can they edit profile -->
      {% if user.is_authenticated and user.pokemon_profile.id == profile.id %}
        <a href="{% url 'update_profile' profile.pk %}" class="a-link">Edit Profile</a>
      {% endif %}
    </div>
  </div>
  
</div>
{% endblock %}

pokemon_app/templates/pokemon_app/view_all_trades.html
<!-- 
 File: view_all_trades.html
 Author: John kim (johnjk@bu.edu), 12/09/2024
 Description: this file is the form to view all trades
-->
{% extends 'pokemon_app/base.html' %}

{% block content %}
<div class="all-trades-container">
  <h2>All Trades</h2>

  <div class="trades-section">
    <h3>Proposed Trades</h3>
    <ul>
      <!-- fetches the proposed trades as in you offer something for their -->
      {% for trade in proposed_trades %}
      <li>
        <span>You offered {{ trade.pokemon_offer.species.name }} to {{ trade.pokemon_request.trainer.user.username }} for {{ trade.pokemon_request.species.name }}.</span>
        <span>Status: {{ trade.status }}</span>
        <a href="{% url 'trade_detail' trade.pk %}" class="a-link">View Details</a>
      </li>
      {% empty %}
      <li>No proposed trades.</li>
      {% endfor %}
    </ul>
  </div>

  <div class="trades-section">
    <h3>Received Trades</h3>
    <ul>
      <!-- fetches the received trades as in you receive an offer for one of your pokemon -->
      {% for trade in received_trades %}
      <li>
        <span>{{ trade.proposer.user.username }} offered {{ trade.pokemon_offer.species.name }} for your {{ trade.pokemon_request.species.name }}.</span>
        <span>Status: {{ trade.status }}</span>
        <a href="{% url 'trade_detail' trade.pk %}" class="a-link">View Details</a>
      </li>
      {% empty %}
      <li>No received trades.</li>
      {% endfor %}
    </ul>
  </div>
  <div class="trade-profile">
    <a class="a-link" href="{% url 'show_profile' user.pokemon_profile.id %}">Show My Profile</a>
  </div>
</div>
{% endblock %}